apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: grk-app
  name: grk-app
  namespace: dev-grk
spec:
  ports:
  - port: 7878
    protocol: TCP
    targetPort: 8080
  selector:
    app: grk-app
  type: NodePort
status:
  loadBalancer: {}
